name: zanedev
favicon: null
layout_spectrum: 1
typography_spectrum: 0.06727
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbffff'
    - '#91c1ff'
    - '#141821'
    - '#604d53'
    - '#fe889b'
  brandStrength: 0.9568204374518245
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
